# Dependencies
# - markdown:         redcarpet
highlighter:      rouge

# Permalinks
# - permalink:        pretty
# - relative_permalinks: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

title: "David Reed"
tagline: ""
description: "Follow <a href=\"https://micro.blog/davereed\">@davereed on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/davereed\">@davereed on Micro.blog</a>."
baseurl: ""
url: "https://microblog.dave256apps.com"
markdown: "kramdown"
username: "davereed"
microblog_user: "davereed"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "David Reed"
name: "David Reed"
gravatar_hash: "06355f5571dba2f9a0a59d02c16777cd"
avatar: "https://micro.blog/davereed/avatar.jpg"
full_name: "David Reed"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"
site_id: "378"
gems: ["jekyll-paginate"]
itunes_description: "Husband, computer science professor at Capital University, iOS App Developer (Attendance2, reDraw), dog lover, and cyclist."
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "David Reed"
itunes_email: ""
podcast: false